// Code generated by mockery v2.45.0. DO NOT EDIT.

//go:build !compile

package connmng

import (
	proto "github.com/ksysoev/revdial/proto"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockServerConn is an autogenerated mock type for the ServerConn type
type MockServerConn struct {
	mock.Mock
}

type MockServerConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerConn) EXPECT() *MockServerConn_Expecter {
	return &MockServerConn_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *MockServerConn) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockServerConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockServerConn_Expecter) Close() *MockServerConn_Close_Call {
	return &MockServerConn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockServerConn_Close_Call) Run(run func()) *MockServerConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerConn_Close_Call) Return(_a0 error) *MockServerConn_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerConn_Close_Call) RunAndReturn(run func() error) *MockServerConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with given fields:
func (_m *MockServerConn) ID() uuid.UUID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// MockServerConn_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockServerConn_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockServerConn_Expecter) ID() *MockServerConn_ID_Call {
	return &MockServerConn_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockServerConn_ID_Call) Run(run func()) *MockServerConn_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerConn_ID_Call) Return(_a0 uuid.UUID) *MockServerConn_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerConn_ID_Call) RunAndReturn(run func() uuid.UUID) *MockServerConn_ID_Call {
	_c.Call.Return(run)
	return _c
}

// SendConnectCommand provides a mock function with given fields: id
func (_m *MockServerConn) SendConnectCommand(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for SendConnectCommand")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerConn_SendConnectCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendConnectCommand'
type MockServerConn_SendConnectCommand_Call struct {
	*mock.Call
}

// SendConnectCommand is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockServerConn_Expecter) SendConnectCommand(id interface{}) *MockServerConn_SendConnectCommand_Call {
	return &MockServerConn_SendConnectCommand_Call{Call: _e.mock.On("SendConnectCommand", id)}
}

func (_c *MockServerConn_SendConnectCommand_Call) Run(run func(id uuid.UUID)) *MockServerConn_SendConnectCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockServerConn_SendConnectCommand_Call) Return(_a0 error) *MockServerConn_SendConnectCommand_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerConn_SendConnectCommand_Call) RunAndReturn(run func(uuid.UUID) error) *MockServerConn_SendConnectCommand_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function with given fields:
func (_m *MockServerConn) State() proto.State {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 proto.State
	if rf, ok := ret.Get(0).(func() proto.State); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(proto.State)
	}

	return r0
}

// MockServerConn_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockServerConn_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *MockServerConn_Expecter) State() *MockServerConn_State_Call {
	return &MockServerConn_State_Call{Call: _e.mock.On("State")}
}

func (_c *MockServerConn_State_Call) Run(run func()) *MockServerConn_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerConn_State_Call) Return(_a0 proto.State) *MockServerConn_State_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerConn_State_Call) RunAndReturn(run func() proto.State) *MockServerConn_State_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServerConn creates a new instance of MockServerConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerConn {
	mock := &MockServerConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
