name: RevDial CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.23.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Code Lint
        uses: golangci/golangci-lint-action@2e788936b09dd82dc280e845628a40d2ba6b204c
        with:
          version: v1.61.0
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -coverprofile=coverage.out -covermode=atomic -v -race ./...
      - name: Prepare coverage reports
        run: |
          cat coverage.out | grep -v "_mock.go" > coverage.final.out
          mv coverage.final.out coverage.out
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
